const PLOT_WIDTH = window.innerWidth - 40;
const PLOT_HEIGHT = window.innerHeight - 60;
var isoCountries = {
	'Afghanistan': 'AF',
	'Aland Islands': 'AX',
	'Albania': 'AL',
	'Algeria': 'DZ',
	'American Samoa': 'AS',
	'Andorra': 'AD',
	'Angola': 'AO',
	'Anguilla': 'AI',
	'Antarctica': 'AQ',
	'Antigua And Barbuda': 'AG',
	'Argentina': 'AR',
	'Armenia': 'AM',
	'Aruba': 'AW',
	'Australia': 'AU',
	'Austria': 'AT',
	'Azerbaijan': 'AZ',
	'Bahamas': 'BS',
	'Bahrain': 'BH',
	'Bangladesh': 'BD',
	'Barbados': 'BB',
	'Belarus': 'BY',
	'Belgium': 'BE',
	'Belize': 'BZ',
	'Benin': 'BJ',
	'Bermuda': 'BM',
	'Bhutan': 'BT',
	'Bolivia': 'BO',
	'Bosnia and Herz.': 'BA',
	'Botswana': 'BW',
	'Bouvet Island': 'BV',
	'Brazil': 'BR',
	'British Indian Ocean Territory': 'IO',
	'Brunei': 'BN',
	'Bulgaria': 'BG',
	'Burkina Faso': 'BF',
	'Burundi': 'BI',
	'Cambodia': 'KH',
	'Cameroon': 'CM',
	'Canada': 'CA',
	'Cape Verde': 'CV',
	'Cayman Islands': 'KY',
	'Central African Rep.': 'CF',
	'Chad': 'TD',
	'Chile': 'CL',
	'China': 'CN',
	'Christmas Island': 'CX',
	'Cocos (Keeling) Islands': 'CC',
	'Colombia': 'CO',
	'Comoros': 'KM',
	'Congo': 'CG',
	'Dem. Rep. Congo': 'CD',
	'Cook Islands': 'CK',
	'Costa Rica': 'CR',
	'Côte d\'Ivoire': 'CI',
	'Croatia': 'HR',
	'Cuba': 'CU',
	'Cyprus': 'CY',
	'Czechia': 'CZ',
	'Denmark': 'DK',
	'Djibouti': 'DJ',
	'Dominica': 'DM',
	'Dominican Rep.': 'DO',
	'Ecuador': 'EC',
	'Egypt': 'EG',
	'El Salvador': 'SV',
	'Eq. Guinea': 'GQ',
	'Eritrea': 'ER',
	'Estonia': 'EE',
	'Ethiopia': 'ET',
	'Falkland Is.': 'FK',
	'Faroe Islands': 'FO',
	'Fiji': 'FJ',
	'Finland': 'FI',
	'France': 'FR',
	'French Guiana': 'GF',
	'French Polynesia': 'PF',
	'Fr. S. Antarctic Lands': 'TF',
	'Gabon': 'GA',
	'Gambia': 'GM',
	'Georgia': 'GE',
	'Germany': 'DE',
	'Ghana': 'GH',
	'Gibraltar': 'GI',
	'Greece': 'GR',
	'Greenland': 'GL',
	'Grenada': 'GD',
	'Guadeloupe': 'GP',
	'Guam': 'GU',
	'Guatemala': 'GT',
	'Guernsey': 'GG',
	'Guinea': 'GN',
	'Guinea-Bissau': 'GW',
	'Guyana': 'GY',
	'Haiti': 'HT',
	'Heard Island & Mcdonald Islands': 'HM',
	'Holy See (Vatican City State)': 'VA',
	'Honduras': 'HN',
	'Hong Kong': 'HK',
	'Hungary': 'HU',
	'Iceland': 'IS',
	'India': 'IN',
	'Indonesia': 'ID',
	'Iran': 'IR',
	'Iraq': 'IQ',
	'Ireland': 'IE',
	'Isle Of Man': 'IM',
	'Israel': 'IL',
	'Italy': 'IT',
	'Jamaica': 'JM',
	'Japan': 'JP',
	'Jersey': 'JE',
	'Jordan': 'JO',
	'Kazakhstan': 'KZ',
	'Kenya': 'KE',
	'Kiribati': 'KI',
	'Republic of Korea': 'KR',
	'South Korea': 'KR',
	"Democratic People's Republic of Korea": 'KP',
	'North Korea': 'KP',
	'Kuwait': 'KW',
	'Kyrgyzstan': 'KG',
	'Laos': 'LA',
	'Latvia': 'LV',
	'Lebanon': 'LB',
	'Lesotho': 'LS',
	'Liberia': 'LR',
	'Libya': 'LY',
	'Liechtenstein': 'LI',
	'Lithuania': 'LT',
	'Luxembourg': 'LU',
	'Macao': 'MO',
	'Macedonia': 'MK',
	'Madagascar': 'MG',
	'Malawi': 'MW',
	'Malaysia': 'MY',
	'Maldives': 'MV',
	'Mali': 'ML',
	'Malta': 'MT',
	'Marshall Islands': 'MH',
	'Martinique': 'MQ',
	'Mauritania': 'MR',
	'Mauritius': 'MU',
	'Mayotte': 'YT',
	'Mexico': 'MX',
	'Micronesia, Federated States Of': 'FM',
	'Moldova': 'MD',
	'Monaco': 'MC',
	'Mongolia': 'MN',
	'Montenegro': 'ME',
	'Montserrat': 'MS',
	'Morocco': 'MA',
	'Mozambique': 'MZ',
	'Myanmar': 'MM',
	'Namibia': 'NA',
	'Nauru': 'NR',
	'Nepal': 'NP',
	'Netherlands': 'NL',
	'Netherlands Antilles': 'AN',
	'New Caledonia': 'NC',
	'New Zealand': 'NZ',
	'Nicaragua': 'NI',
	'Niger': 'NE',
	'Nigeria': 'NG',
	'Niue': 'NU',
	'Norfolk Island': 'NF',
	'Northern Mariana Islands': 'MP',
	'Norway': 'NO',
	'Oman': 'OM',
	'Pakistan': 'PK',
	'Palau': 'PW',
	'Palestine': 'PS',
	'Panama': 'PA',
	'Papua New Guinea': 'PG',
	'Paraguay': 'PY',
	'Peru': 'PE',
	'Philippines': 'PH',
	'Pitcairn': 'PN',
	'Poland': 'PL',
	'Portugal': 'PT',
	'Puerto Rico': 'PR',
	'Qatar': 'QA',
	'Reunion': 'RE',
	'Romania': 'RO',
	'Russia': 'RU',
	'Rwanda': 'RW',
	'Saint Barthelemy': 'BL',
	'Saint Helena': 'SH',
	'Saint Kitts And Nevis': 'KN',
	'Saint Lucia': 'LC',
	'Saint Martin': 'MF',
	'Saint Pierre And Miquelon': 'PM',
	'Saint Vincent And Grenadines': 'VC',
	'Samoa': 'WS',
	'San Marino': 'SM',
	'Sao Tome And Principe': 'ST',
	'Saudi Arabia': 'SA',
	'Senegal': 'SN',
	'Serbia': 'RS',
	'Seychelles': 'SC',
	'Sierra Leone': 'SL',
	'Singapore': 'SG',
	'Slovakia': 'SK',
	'Slovenia': 'SI',
	'Solomon Is.': 'SB',
	'Somalia': 'SO',
	'South Africa': 'ZA',
	'South Georgia And Sandwich Isl.': 'GS',
	'Spain': 'ES',
	'Sri Lanka': 'LK',
	'Sudan': 'SD',
	'S. Sudan': 'SS',
	'Suriname': 'SR',
	'Svalbard And Jan Mayen': 'SJ',
	'Swaziland': 'SZ',
	'eSwatini': 'SZ',
	'Sweden': 'SE',
	'Switzerland': 'CH',
	'Syria': 'SY',
	'Taiwan': 'TW',
	'Tajikistan': 'TJ',
	'Tanzania': 'TZ',
	'Thailand': 'TH',
	'Timor-Leste': 'TL',
	'Togo': 'TG',
	'Tokelau': 'TK',
	'Tonga': 'TO',
	'Trinidad and Tobago': 'TT',
	'Tunisia': 'TN',
	'Turkey': 'TR',
	'Turkmenistan': 'TM',
	'Turks And Caicos Islands': 'TC',
	'Tuvalu': 'TV',
	'Uganda': 'UG',
	'Ukraine': 'UA',
	'United Arab Emirates': 'AE',
	'United Kingdom': 'GB',
	'United States of America': 'US',
	'United States Outlying Islands': 'UM',
	'Uruguay': 'UY',
	'Uzbekistan': 'UZ',
	'Vanuatu': 'VU',
	'Venezuela': 'VE',
	'Vietnam': 'VN',
	'Virgin Islands, British': 'VG',
	'Virgin Islands, U.S.': 'VI',
	'Wallis And Futuna': 'WF',
	'W. Sahara': 'EH',
	'Yemen': 'YE',
	'Zambia': 'ZM',
	'Zimbabwe': 'ZW'
};

const iso2Toiso3 = {
	"AF": "AFG",
	"AX": "ALA",
	"AL": "ALB",
	"DZ": "DZA",
	"AS": "ASM",
	"AD": "AND",
	"AO": "AGO",
	"AI": "AIA",
	"AQ": "ATA",
	"AG": "ATG",
	"AR": "ARG",
	"AM": "ARM",
	"AW": "ABW",
	"AU": "AUS",
	"AT": "AUT",
	"AZ": "AZE",
	"BS": "BHS",
	"BH": "BHR",
	"BD": "BGD",
	"BB": "BRB",
	"BY": "BLR",
	"BE": "BEL",
	"BZ": "BLZ",
	"BJ": "BEN",
	"BM": "BMU",
	"BT": "BTN",
	"BO": "BOL",
	"BQ": "BES",
	"BA": "BIH",
	"BW": "BWA",
	"BV": "BVT",
	"BR": "BRA",
	"IO": "IOT",
	"BN": "BRN",
	"BG": "BGR",
	"BF": "BFA",
	"BI": "BDI",
	"CV": "CPV",
	"KH": "KHM",
	"CM": "CMR",
	"CA": "CAN",
	"KY": "CYM",
	"CF": "CAF",
	"TD": "TCD",
	"CL": "CHL",
	"CN": "CHN",
	"CX": "CXR",
	"CC": "CCK",
	"CO": "COL",
	"KM": "COM",
	"CG": "COG",
	"CD": "COD",
	"CK": "COK",
	"CR": "CRI",
	"CI": "CIV",
	"HR": "HRV",
	"CU": "CUB",
	"CW": "CUW",
	"CY": "CYP",
	"CZ": "CZE",
	"DK": "DNK",
	"DJ": "DJI",
	"DM": "DMA",
	"DO": "DOM",
	"EC": "ECU",
	"EG": "EGY",
	"SV": "SLV",
	"GQ": "GNQ",
	"ER": "ERI",
	"EE": "EST",
	"ET": "ETH",
	"FK": "FLK",
	"FO": "FRO",
	"FJ": "FJI",
	"FI": "FIN",
	"FR": "FRA",
	"GF": "GUF",
	"PF": "PYF",
	"TF": "ATF",
	"GA": "GAB",
	"GM": "GMB",
	"GE": "GEO",
	"DE": "DEU",
	"GH": "GHA",
	"GI": "GIB",
	"GR": "GRC",
	"GL": "GRL",
	"GD": "GRD",
	"GP": "GLP",
	"GU": "GUM",
	"GT": "GTM",
	"GG": "GGY",
	"GN": "GIN",
	"GW": "GNB",
	"GY": "GUY",
	"HT": "HTI",
	"HM": "HMD",
	"VA": "VAT",
	"HN": "HND",
	"HK": "HKG",
	"HU": "HUN",
	"IS": "ISL",
	"IN": "IND",
	"ID": "IDN",
	"IR": "IRN",
	"IQ": "IRQ",
	"IE": "IRL",
	"IM": "IMN",
	"IL": "ISR",
	"IT": "ITA",
	"JM": "JAM",
	"JP": "JPN",
	"JE": "JEY",
	"JO": "JOR",
	"KZ": "KAZ",
	"KE": "KEN",
	"KI": "KIR",
	"KP": "PRK",
	"KR": "KOR",
	"KW": "KWT",
	"KG": "KGZ",
	"LA": "LAO",
	"LV": "LVA",
	"LB": "LBN",
	"LS": "LSO",
	"LR": "LBR",
	"LY": "LBY",
	"LI": "LIE",
	"LT": "LTU",
	"LU": "LUX",
	"MO": "MAC",
	"MK": "MKD",
	"MG": "MDG",
	"MW": "MWI",
	"MY": "MYS",
	"MV": "MDV",
	"ML": "MLI",
	"MT": "MLT",
	"MH": "MHL",
	"MQ": "MTQ",
	"MR": "MRT",
	"MU": "MUS",
	"YT": "MYT",
	"MX": "MEX",
	"FM": "FSM",
	"MD": "MDA",
	"MC": "MCO",
	"MN": "MNG",
	"ME": "MNE",
	"MS": "MSR",
	"MA": "MAR",
	"MZ": "MOZ",
	"MM": "MMR",
	"NA": "NAM",
	"NR": "NRU",
	"NP": "NPL",
	"NL": "NLD",
	"NC": "NCL",
	"NZ": "NZL",
	"NI": "NIC",
	"NE": "NER",
	"NG": "NGA",
	"NU": "NIU",
	"NF": "NFK",
	"MP": "MNP",
	"NO": "NOR",
	"OM": "OMN",
	"PK": "PAK",
	"PW": "PLW",
	"PS": "PSE",
	"PA": "PAN",
	"PG": "PNG",
	"PY": "PRY",
	"PE": "PER",
	"PH": "PHL",
	"PN": "PCN",
	"PL": "POL",
	"PT": "PRT",
	"PR": "PRI",
	"QA": "QAT",
	"RE": "REU",
	"RO": "ROU",
	"RU": "RUS",
	"RW": "RWA",
	"BL": "BLM",
	"SH": "SHN",
	"KN": "KNA",
	"LC": "LCA",
	"MF": "MAF",
	"PM": "SPM",
	"VC": "VCT",
	"WS": "WSM",
	"SM": "SMR",
	"ST": "STP",
	"SA": "SAU",
	"SN": "SEN",
	"RS": "SRB",
	"SC": "SYC",
	"SL": "SLE",
	"SG": "SGP",
	"SX": "SXM",
	"SK": "SVK",
	"SI": "SVN",
	"SB": "SLB",
	"SO": "SOM",
	"ZA": "ZAF",
	"GS": "SGS",
	"SS": "SSD",
	"ES": "ESP",
	"LK": "LKA",
	"SD": "SDN",
	"SR": "SUR",
	"SJ": "SJM",
	"SZ": "SWZ",
	"SE": "SWE",
	"CH": "CHE",
	"SY": "SYR",
	"TW": "TWN",
	"TJ": "TJK",
	"TZ": "TZA",
	"TH": "THA",
	"TL": "TLS",
	"TG": "TGO",
	"TK": "TKL",
	"TO": "TON",
	"TT": "TTO",
	"TN": "TUN",
	"TR": "TUR",
	"TM": "TKM",
	"TC": "TCA",
	"TV": "TUV",
	"UG": "UGA",
	"UA": "UKR",
	"AE": "ARE",
	"GB": "GBR",
	"US": "USA",
	"UM": "UMI",
	"UY": "URY",
	"UZ": "UZB",
	"VU": "VUT",
	"VE": "VEN",
	"VN": "VNM",
	"VG": "VGB",
	"VI": "VIR",
	"WF": "WLF",
	"EH": "ESH",
	"YE": "YEM",
	"ZM": "ZMB",
	"ZW": "ZWE"
}


const init = async () => {
	await Promise.all([d3.csv('../data/csv/Aggregate_federal_spending_country_month_agency.csv'),
	d3.json('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json')]).then(data => {
		const spending = data[0];
		const world = data[1];

		const projection = d3.geoEqualEarth().scale(400);

		projection
			.scale(1)
			.translate([0, 0]);

		const countries = topojson.feature(world, world.objects['countries']).features
		const path = d3.geoPath().projection(projection);

		const b = [[-1.5, -1.5], [1.5, 1.5]],
			s = .95 / Math.max((b[1][0] - b[0][0]) / PLOT_WIDTH, (b[1][1] - b[0][1]) / PLOT_HEIGHT),
			t = [(PLOT_WIDTH - s * (b[1][0] + b[0][0])) / 2, (PLOT_HEIGHT - s * (b[1][1] + b[0][1])) / 2];
		projection
			.scale(s)
			.translate(t);

		const svg = d3.select('#map_svg').attr('width', PLOT_WIDTH).attr('height', PLOT_HEIGHT);

		const list_spending_by_country = d3.nest()
			.key(function(d) { return d['country']; })
			.rollup(v => d3.sum(v, d => d['sum']))
			.entries(spending);

		const spending_by_country = {};
		list_spending_by_country.forEach(d => {
			spending_by_country[d['key']] = d['value']
		})

		const color = d3.scaleThreshold()
			.domain([
				Math.pow(10, 6),
				Math.pow(10, 7),
				Math.pow(10, 8),
				Math.pow(10, 9),
				Math.pow(10, 10),
				Math.pow(10, 11),
				Math.pow(10, 12),])
			.range(d3.schemeGreens[7]);

		svg.append("g")
			.selectAll("path")
			.data(countries)
			.join("path")
			.attr("fill", d => {
				if (isoCountries[d['properties']['name']] === undefined) {
					return "#ccc"; // Can't find ISO 2
				}
				if (iso2Toiso3[isoCountries[d['properties']['name']]] === undefined) {
					return "#ccc"; // Can't find ISO 3
				}
				if (spending_by_country[iso2Toiso3[isoCountries[d['properties']['name']]]] === undefined) {
					return "#fff"
				}

				return color(spending_by_country[iso2Toiso3[isoCountries[d['properties']['name']]]]);
			})
			.attr('stroke', "#000")
			.attr("d", path);
	});
};

window.onload = () => {
	init();
}
